[package]
name = "day01_part01"
version = "0.1.0"
authors = ["Rodrigo Theodoro <theodoro.biotec@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
itertools = "0.10.3"
