[package]
name = "day04"
version = "0.1.0"
authors = ["Rodrigo Theodoro <theodoro.biotec@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
ndarray = "0.15.4"
nom = "7.1.0"
